# Generated by Django 2.1.5 on 2019-02-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
